import type { Phone } from "@/types/phone";

export const phones: Phone[] = [
  {
    brand: "Apple",
    name: "iPhone 16 Pro",
    yearStart: 2024,
    yearEnd: null,
    kept: true,
    liked: true,
    image: "/phones/apple-iphone-16-pro.png",
  },
  {
    brand: "Apple",
    name: "iPhone 13 mini",
    yearStart: 2023,
    yearEnd: 2024,
    kept: false,
    liked: true,
    image: "/phones/apple-iphone-13-mini.jpg",
  },
  {
    brand: "Google",
    name: "Pixel 7",
    yearStart: 2022,
    yearEnd: 2023,
    kept: false,
    liked: true,
    image: "/phones/google-pixel-7.jpg",
  },
  {
    brand: "Google",
    name: "Pixel 5",
    yearStart: 2020,
    yearEnd: 2022,
    kept: false,
    liked: true,
    image: "/phones/google-pixel-5.jpg",
  },
  {
    brand: "Google",
    name: "Pixel 2",
    yearStart: 2018,
    yearEnd: 2020,
    kept: false,
    liked: true,
    image: "/phones/google-pixel-2.jpg",
  },
  {
    brand: "Sony",
    name: "Xperia X Compact",
    yearStart: 2017,
    yearEnd: 2018,
    kept: false,
    liked: true,
    image: "/phones/sony-xperia-x-compact.jpg",
  },
  {
    brand: "Sony",
    name: "XZ Premium",
    yearStart: 2017,
    yearEnd: 2017,
    kept: false,
    liked: false,
    image: "/phones/sony-xperia-xz-premium.jpg",
  },
  {
    brand: "LG",
    name: "G5",
    yearStart: 2016,
    yearEnd: 2017,
    kept: false,
    liked: false,
    image: "/phones/lg-g5.jpg",
  },
  {
    brand: "Sony",
    name: "Z3 Compact",
    yearStart: 2015,
    yearEnd: 2016,
    kept: false,
    liked: true,
    image: "/phones/sony-xperia-z3-compact.jpg",
  },
  {
    brand: "Sony",
    name: "Xperia Z2",
    yearStart: 2014,
    yearEnd: 2015,
    kept: false,
    liked: true,
    image: "/phones/sony-xperia-z2.jpg",
  },
  {
    brand: "Nokia",
    name: "Lumia 925",
    yearStart: 2013,
    yearEnd: 2014,
    kept: false,
    liked: false,
    image: "/phones/nokia-lumia-925.jpg",
  },
  {
    brand: "Samsung",
    name: "Note 2",
    yearStart: 2013,
    yearEnd: 2013,
    kept: false,
    liked: true,
    image: "/phones/samsung-galaxy-note-ii-n7105.jpg",
  },
  {
    brand: "Samsung",
    name: "Google Nexus S",
    yearStart: 2012,
    yearEnd: 2013,
    kept: false,
    liked: false,
    image: "/phones/samsung-google-nexus-s.jpg",
  },
  {
    brand: "Samsung",
    name: "Xcover 271",
    yearStart: 2012,
    yearEnd: 2012,
    kept: false,
    liked: true,
    image: "/phones/samsung-xcover-271.jpg",
  },
  {
    brand: "Samsung",
    name: "Galaxy S2",
    yearStart: 2011,
    yearEnd: 2012,
    kept: false,
    liked: true,
    image: "/phones/samsung-i9100-galaxy-s-ii.jpg",
  },
  {
    brand: "HTC",
    name: "Desire Z",
    yearStart: 2011,
    yearEnd: 2011,
    kept: false,
    liked: true,
    image: "/phones/htc-desire-z.jpg",
  },
  {
    brand: "HTC",
    name: "Desire",
    yearStart: 2010,
    yearEnd: 2011,
    kept: false,
    liked: false,
    image: "/phones/htc-desire.jpg",
  },
  {
    brand: "Apple",
    name: "iPhone 3G",
    yearStart: 2008,
    yearEnd: 2010,
    kept: false,
    liked: false,
    image: "/phones/apple-iphone-3g.jpg",
  },
  {
    brand: "Nokia",
    name: "1110i",
    yearStart: 2006,
    yearEnd: 2008,
    kept: false,
    liked: true,
    image: "/phones/nokia-1110i.jpg",
  },
  {
    brand: "Nokia",
    name: "N90",
    yearStart: 2005,
    yearEnd: 2006,
    kept: false,
    liked: false,
    image: "/phones/nokia-n90.jpg",
  },
  {
    brand: "Motorola",
    name: "RAZR V3",
    yearStart: 2004,
    yearEnd: 2005,
    kept: false,
    liked: true,
    image: "/phones/motorola-razr-v3.jpg",
  },
  {
    brand: "Nokia",
    name: "3330",
    yearStart: 2002,
    yearEnd: 2004,
    kept: false,
    liked: true,
    image: "/phones/nokia-3330.png",
  },
  {
    brand: "Nokia",
    name: "3310",
    yearStart: 2000,
    yearEnd: 2002,
    kept: true,
    liked: true,
    image: "/phones/nokia-3310.png",
  },
];
